project:
  title: "template for Histopathology Atlas (Patoloji AtlasÄ±)"
  output-dir: docs

editor: visual

execute:
  freeze: false

format:
  gfm:
    preview-mode: raw
#  pdf: default
#  epub: default
  html: default
